# Generated by Django 6.0.2 on 2026-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='education_weight',
            field=models.FloatField(default=0.2, help_text='Weight for education match (default 20%)'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='experience_weight',
            field=models.FloatField(default=0.1, help_text='Weight for experience match (default 10%)'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='semantic_weight',
            field=models.FloatField(default=0.2, help_text='Weight for semantic similarity (default 20%)'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='skill_weight',
            field=models.FloatField(default=0.5, help_text='Weight for skill overlap (default 50%)'),
        ),
    ]
